ALTER TABLE ospos_items
ADD custom1 VARCHAR(25) NOT NULL,
ADD custom2 VARCHAR(25) NOT NULL,
ADD custom3 VARCHAR(25) NOT NULL,
ADD custom4 VARCHAR(25) NOT NULL,
ADD custom5 VARCHAR(25) NOT NULL,
ADD custom6 VARCHAR(25) NOT NULL,
ADD custom7 VARCHAR(25) NOT NULL,
ADD custom8 VARCHAR(25) NOT NULL,
ADD custom9 VARCHAR(25) NOT NULL,
ADD custom10 VARCHAR(25) NOT NULL;

ALTER TABLE ospos_giftcards ADD person_id INT NOT NULL;
